[{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"../../src/types\"' has no exported member 'Customer'.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 19,
	"endLineNumber": 8,
	"endColumn": 27
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"../../src/types\"' has no exported member 'Order'.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 29,
	"endLineNumber": 8,
	"endColumn": 34
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{}' is missing the following properties from type 'HomeScreenProps': salesHistory, products",
	"source": "ts",
	"startLineNumber": 47,
	"startColumn": 28,
	"endLineNumber": 47,
	"endColumn": 38
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2740",
	"severity": 8,
	"message": "Type '{}' is missing the following properties from type 'POSScreenProps': products, cart, addToCart, openEditProductModal, and 8 more.",
	"source": "ts",
	"startLineNumber": 48,
	"startColumn": 27,
	"endLineNumber": 48,
	"endColumn": 36
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{}' is missing the following properties from type 'ProductsScreenProps': products, onAddProduct, onEditProduct, onDeleteProduct",
	"source": "ts",
	"startLineNumber": 49,
	"startColumn": 32,
	"endLineNumber": 49,
	"endColumn": 46
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2739",
	"severity": 8,
	"message": "Type '{}' is missing the following properties from type 'HomeScreenProps': salesHistory, products",
	"source": "ts",
	"startLineNumber": 56,
	"startColumn": 24,
	"endLineNumber": 56,
	"endColumn": 34
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ onLoginSuccess: () => void; }' is not assignable to type 'IntrinsicAttributes'.\n  Property 'onLoginSuccess' does not exist on type 'IntrinsicAttributes'.",
	"source": "ts",
	"startLineNumber": 62,
	"startColumn": 25,
	"endLineNumber": 62,
	"endColumn": 39
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ toggleSidebar: () => void; user: { name: string; role: string; }; }' is not assignable to type 'IntrinsicAttributes & HeaderProps'.\n  Property 'toggleSidebar' does not exist on type 'IntrinsicAttributes & HeaderProps'.",
	"source": "ts",
	"startLineNumber": 71,
	"startColumn": 9,
	"endLineNumber": 71,
	"endColumn": 22
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ activeTab: string; onTabChange: (tab: string) => void; tabs: string[]; }' is not assignable to type 'IntrinsicAttributes & SidebarProps'.\n  Property 'activeTab' does not exist on type 'IntrinsicAttributes & SidebarProps'.",
	"source": "ts",
	"startLineNumber": 79,
	"startColumn": 13,
	"endLineNumber": 79,
	"endColumn": 22
},{
	"resource": "/home/user/pos-app/app/(tabs)/index.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ status: string; version: string; }' is not assignable to type 'IntrinsicAttributes & FooterProps'.\n  Property 'status' does not exist on type 'IntrinsicAttributes & FooterProps'.",
	"source": "ts",
	"startLineNumber": 93,
	"startColumn": 15,
	"endLineNumber": 93,
	"endColumn": 21
}]